################################################
#  Settings used by BOTH server and client     #
################################################

port: 44394
movement-speed: 0.1		#Units player can advance per tick
rotate-speed: 0.005		#Radians player can rotate per tick

################################################
#  Settings used by just the SERVER            #
################################################

player-shape: -1 -2 1 -2 0 3
server-timer-resolution: 20	#Milliseconds per game tick
player-color: 1 100 50 255
max-players: 20


################################################
#  Settings used by just the CLIENT            #
################################################

host:  10.231.169.127		#Address to connect to
client-timer-resolution: 50
start-brush: default	#Which brush to start on
screen-width: 75		#Screen % width on open
screen-height: 75		#Screen % height on open
