########################################################
#      Settings used by BOTH server and client         #
########################################################

port: 44394
movement-speed: 0.1			#Units player can advance per tick
rotate-speed: 0.02			#Radians player can rotate per tick

########################################################
#      Settings used by just the SERVER                #
########################################################

player-shape: -1 -2 1 -2 0 3
server-timer-resolution: 20	#Milliseconds per game tick
player-color: 1 100 50 255	#In RGBa format
max-players: 20				#How many players may join

ink-types:
 - {name: blue, starting: 100, capacity: 100, refill-rate: 2.0, color: 10 10 255 255}
 - {name: white, starting: 50, capacity: 100, refill-rate: 0.1, color: 255 255 255 255}
 - {name: black, starting: 20, capacity: 1000, refill-rate: 1, color: 0 0 0 255}

########################################################
#      Settings used by just the CLIENT                #
########################################################

host:  10.231.169.127		#Address to connect to
client-timer-resolution: 50	#Too high/low = lag
start-brush: default		#Which brush to start on
screen-width: 75			#Screen % width on open
screen-height: 75			#Screen % height on open
scale: 30					#Pixel to board unit ratio
mouse-sampling-distance: 3	#How precise mouse sampling is

key-up: W,UP
key-down: S,DOWN
key-left: A,LEFT
key-right: D,RIGHT
key-rotate-clock: E
key-rotate-counter: Q
