################################################
#  Settings used by BOTH server and client     #
################################################

port: 44394
timer-resolution: 10	#Milliseconds per game tick
movement-speed: 1		#Speed player can move per tick


################################################
#  Settings used by just the SERVER            #
################################################

player-shape: 0 0 2 0 1 5
player-color: 1 100 50 255
max-players: 20


################################################
#  Settings used by just the CLIENT            #
################################################

host:  10.231.169.127		#Address to connect to
start-brush: default	#Which brush to start on
screen-width: 75		#Screen % width on open
screen-height: 75		#Screen % height on open